/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plans/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_api_plans_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Step 4 — SchemaAnalyzer LLM agent.
         */
        post: operations["analyze_api_plans_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/architect-bv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Architect Bv
         * @description Step 4b — BV Architect (deterministic).
         */
        post: operations["architect_bv_api_plans_architect_bv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Step 5 — YAML Generator (deterministic).
         */
        post: operations["generate_api_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_plans__plan_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_plans__plan_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Changes */
        post: operations["request_changes_api_plans__plan_id__request_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recent */
        get: operations["list_recent_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History For */
        get: operations["history_for_api_history__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_catalogs_api_discovery_catalogs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/catalogs/{catalog}/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_schemas_api_discovery_catalogs__catalog__schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["snapshot_api_discovery_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/submit-for-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit_for_review_api_plans__plan_id__submit_for_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyzeRequest
         * @description Inputs for Step 4 — Schema Analyzer.
         *
         *     ``system`` and ``bronze`` are produced by the discovery + bronze-reader
         *     steps; ``change_set`` is the diff analyzer's output. The UI fetches
         *     them via earlier endpoints and re-posts them here so the call is
         *     explicit and the API stays stateless.
         */
        AnalyzeRequest: {
            system: components["schemas"]["SourceSystem"];
            bronze: components["schemas"]["BronzeSnapshot"];
            change_set: components["schemas"]["ChangeSet"];
        };
        VaultColumn: {
            name: string;
            raw_dtype: string;
            nullable: boolean;
            comment?: string | null;
        };
        VaultEntity: {
            name: string;
            kind: string;
            columns: components["schemas"]["VaultColumn"][];
        };
        CatalogSnapshot: {
            catalog: string;
            schema_name: string;
            captured_at: string;
            entities: components["schemas"]["VaultEntity"][];
            metadata_yaml_path?: string | null;
        };
        CatalogListResponse: {
            catalogs: string[];
        };
        SchemaListResponse: {
            catalog: string;
            schemas: string[];
        };
        SnapshotRequest: {
            catalog: string;
            bronze_schema: string;
            vault_schema: string;
            system_id?: string | null;
            system_name?: string | null;
            record_source?: string | null;
            metadata_yaml_path?: string | null;
            include_patterns?: string[];
            exclude_patterns?: string[];
        };
        SnapshotResponse: {
            system: components["schemas"]["SourceSystem"];
            catalog_snapshot: components["schemas"]["CatalogSnapshot"];
            bronze_snapshot: components["schemas"]["BronzeSnapshot"];
            change_set: components["schemas"]["ChangeSet"];
        };
        SubmitForReviewRequest: {
            plan: components["schemas"]["ModelingPlan"];
            rendered_yaml: string;
            validation: components["schemas"]["ValidationReport"];
        };
        /**
         * ApprovalRecord
         * @description A single row in the approval store.
         *
         *     ``plan_id`` is a deterministic content hash of the generated plan
         *     (see :func:`dbt_builder.src.ai.utils.ids.stable_id`) so identical inputs
         *     yield identical IDs across runs — this is what makes the approval gate
         *     idempotent. ``parent_plan_id`` links edited plans back to the version they
         *     were derived from, forming an audit chain.
         */
        ApprovalRecord: {
            /** Plan Id */
            plan_id: string;
            /**
             * Version
             * @description Monotonically increasing per plan_id.
             */
            version: number;
            status: components["schemas"]["ApprovalStatus"];
            /**
             * Actor
             * @description UPN / email of the user who triggered this transition.
             */
            actor: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Comment */
            comment?: string | null;
            /**
             * Plan Json
             * @description Serialised ModelingPlan at the time of the transition.
             */
            plan_json: string;
            /**
             * Validation Json
             * @description Serialised ValidationReport that accompanied the plan.
             */
            validation_json?: string | null;
            /**
             * Parent Plan Id
             * @description plan_id of the version this record was derived from (edit chain).
             */
            parent_plan_id?: string | null;
        };
        /**
         * ApprovalStatus
         * @description Lifecycle of a generated plan from the reviewer's perspective.
         * @enum {string}
         */
        ApprovalStatus: "draft" | "approved" | "rejected" | "changes_requested";
        /**
         * BridgeTable
         * @description Bridge table proposal — one per link with ≥2 hub references.
         */
        BridgeTable: {
            /**
             * Name
             * @description dbt model name, e.g. ``br_terminal_node``.
             */
            name: string;
            /** Parent Link */
            parent_link: string;
            /**
             * Hub Keys
             * @description Ordered hub names the bridge resolves between.
             */
            hub_keys: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /**
         * BronzeColumn
         * @description A single column described by ``DESCRIBE TABLE`` on the bronze layer.
         */
        BronzeColumn: {
            /** Name */
            name: string;
            /** Raw Dtype */
            raw_dtype: string;
            /**
             * Nullable
             * @default true
             */
            nullable: boolean;
            /** Comment */
            comment?: string | null;
            /**
             * Is Partition
             * @default false
             */
            is_partition: boolean;
        };
        /**
         * BronzeSnapshot
         * @description Output of Step 2 — Bronze Schema Reader.
         */
        BronzeSnapshot: {
            /** Catalog */
            catalog: string;
            /** Schema Name */
            schema_name: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /**
             * Tables
             * @default []
             */
            tables: components["schemas"]["BronzeTable"][];
            /**
             * Missing Business Keys
             * @description Bronze table names that lack a recognisable business-key column.
             * @default []
             */
            missing_business_keys: string[];
        };
        /**
         * BronzeTable
         * @description A single bronze table snapshot.
         */
        BronzeTable: {
            /** Catalog */
            catalog: string;
            /** Schema Name */
            schema_name: string;
            /** Name */
            name: string;
            /** Columns */
            columns: components["schemas"]["BronzeColumn"][];
            /**
             * Business Key
             * @description Detected business-key column (mrid / *_id / *_key); None if absent.
             */
            business_key?: string | null;
        };
        /**
         * BvProposal
         * @description Aggregate output of the BV Architect.
         */
        BvProposal: {
            /** System Id */
            system_id: string;
            /**
             * Pit Tables
             * @default []
             */
            pit_tables: components["schemas"]["PitTable"][];
            /**
             * Bridge Tables
             * @default []
             */
            bridge_tables: components["schemas"]["BridgeTable"][];
            /**
             * Bv Satellites
             * @default []
             */
            bv_satellites: components["schemas"]["BvSatellite"][];
        };
        /**
         * BvSatellite
         * @description Derived / business-rule satellite proposal.
         *
         *     Unlike a raw-vault satellite, the payload columns here are *new*
         *     expressions (``computed_columns``) the LLM proposes, not source
         *     columns. The Validator and the YAML Generator will refuse a BvSatellite
         *     whose computed columns collide with raw-vault payload columns.
         */
        BvSatellite: {
            /**
             * Name
             * @description dbt model name, e.g. ``bv_sat_terminal_score``.
             */
            name: string;
            /** Parent Hub */
            parent_hub: string;
            /**
             * Source Models
             * @description Raw-vault models this BV sat reads from.
             */
            source_models: string[];
            /**
             * Computed Columns
             * @description Names of derived columns produced by the BV sat.
             */
            computed_columns: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /**
         * ChangeCategory
         * @description How a single bronze table relates to the existing vault.
         * @enum {string}
         */
        ChangeCategory: "new" | "drift" | "unchanged" | "orphaned";
        /**
         * ChangeRisk
         * @description Coarse risk level for a single change. Drives pipeline halt vs warn.
         * @enum {string}
         */
        ChangeRisk: "low" | "medium" | "high";
        /**
         * ChangeSet
         * @description Output of Step 3 — Diff Analyzer.
         */
        ChangeSet: {
            /** Catalog */
            catalog: string;
            /** Schema Name */
            schema_name: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["TableChange"][];
        };
        /**
         * CheckSummary
         * @description Aggregate counts per severity, used by the UI banner.
         */
        CheckSummary: {
            /**
             * Errors
             * @default 0
             */
            errors: number;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
            /**
             * Infos
             * @default 0
             */
            infos: number;
        };
        /**
         * ColumnDiff
         * @description Per-column diff between bronze and the matching vault entity.
         */
        ColumnDiff: {
            /** Name */
            name: string;
            /**
             * Change
             * @description added | removed | type_changed
             */
            change: string;
            /** Old Dtype */
            old_dtype?: string | null;
            /** New Dtype */
            new_dtype?: string | null;
        };
        /** CommentBody */
        CommentBody: {
            /** Comment */
            comment?: string | null;
        };
        /**
         * DecisionConfidence
         * @description Coarse self-reported confidence from the modelling agent.
         *
         *     Kept ordinal (LOW / MEDIUM / HIGH) rather than numeric to discourage
         *     over-precision in LLM output and to make human review thresholds simple.
         * @enum {string}
         */
        DecisionConfidence: "low" | "medium" | "high";
        /**
         * EntityKind
         * @description Closed taxonomy of Data Vault 2 raw-vault entity kinds.
         * @enum {string}
         */
        EntityKind: "hub" | "link" | "satellite";
        /**
         * GenerateRequest
         * @description Inputs for Step 5 — YAML Generator.
         */
        GenerateRequest: {
            plan: components["schemas"]["ModelingPlan-Input"];
            bv?: components["schemas"]["BvProposal"] | null;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Files */
            files: components["schemas"]["GeneratedYamlFile"][];
        };
        /**
         * GeneratedYamlFile
         * @description API-friendly view of a YamlFile (text body, not bytes).
         */
        GeneratedYamlFile: {
            /** Path */
            path: string;
            /**
             * Body
             * @description UTF-8 decoded YAML content.
             */
            body: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HubDecision
         * @description A proposed raw-vault Hub.
         *
         *     A hub captures the **business-key identity** of a core entity. The
         *     ``business_keys`` list normally has length 1; composite keys are allowed
         *     when the source genuinely has no surrogate.
         */
        HubDecision: {
            /**
             * Name
             * @description Target dbt model name, e.g. 'hub_conducting_equipment'.
             */
            name: string;
            /**
             * Source Table
             * @description Bare or fully-qualified source table this entity is derived from.
             */
            source_table: string;
            /** @default medium */
            confidence: components["schemas"]["DecisionConfidence"];
            /**
             * Rationale
             * @description Free-text justification produced by the agent (kept short).
             * @default
             */
            rationale: string;
            /** @default hub */
            kind: components["schemas"]["EntityKind"];
            /**
             * Business Keys
             * @description Source column(s) forming the business key.
             */
            business_keys: string[];
            /**
             * Hash Key
             * @description Deterministic hash key column name, e.g. 'HK_CONDUCTING_EQUIPMENT'.
             */
            hash_key: string;
        };
        /**
         * LinkDecision
         * @description A proposed raw-vault Link relating two or more hubs.
         */
        LinkDecision: {
            /**
             * Name
             * @description Target dbt model name, e.g. 'hub_conducting_equipment'.
             */
            name: string;
            /**
             * Source Table
             * @description Bare or fully-qualified source table this entity is derived from.
             */
            source_table: string;
            /** @default medium */
            confidence: components["schemas"]["DecisionConfidence"];
            /**
             * Rationale
             * @description Free-text justification produced by the agent (kept short).
             * @default
             */
            rationale: string;
            /** @default link */
            kind: components["schemas"]["EntityKind"];
            /**
             * Hash Key
             * @description Composite hash-key column for the link, e.g. 'HK_TERMINAL_EQUIPMENT_NODE'.
             */
            hash_key: string;
            /**
             * Fk Columns
             * @description Ordered hub hash-key columns participating in the link.
             */
            fk_columns: string[];
        };
        /**
         * ModelingPlan
         * @description The full set of entity decisions produced for one source system.
         *
         *     Cross-entity invariants are enforced by ``model_validator``:
         *
         *     * hub names are unique;
         *     * every satellite's ``parent_hub`` references a known hub in the same plan;
         *     * link / satellite names do not collide with hub names.
         *
         *     These checks let the rendering layer assume a well-formed plan and avoid
         *     re-validating in multiple downstream steps.
         */
        "ModelingPlan-Input": {
            /** System Id */
            system_id: string;
            /**
             * Hubs
             * @default []
             */
            hubs: components["schemas"]["HubDecision"][];
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["LinkDecision"][];
            /**
             * Satellites
             * @default []
             */
            satellites: components["schemas"]["SatelliteDecision"][];
        };
        /**
         * ModelingPlan
         * @description The full set of entity decisions produced for one source system.
         *
         *     Cross-entity invariants are enforced by ``model_validator``:
         *
         *     * hub names are unique;
         *     * every satellite's ``parent_hub`` references a known hub in the same plan;
         *     * link / satellite names do not collide with hub names.
         *
         *     These checks let the rendering layer assume a well-formed plan and avoid
         *     re-validating in multiple downstream steps.
         */
        "ModelingPlan-Output": {
            /** System Id */
            system_id: string;
            /**
             * Hubs
             * @default []
             */
            hubs: components["schemas"]["HubDecision"][];
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["LinkDecision"][];
            /**
             * Satellites
             * @default []
             */
            satellites: components["schemas"]["SatelliteDecision"][];
        };
        /**
         * PitTable
         * @description Point-in-time table proposal — one per hub with multiple satellites.
         */
        PitTable: {
            /**
             * Name
             * @description dbt model name, e.g. ``pit_terminal``.
             */
            name: string;
            /** Parent Hub */
            parent_hub: string;
            /**
             * Satellites
             * @description Names of satellite models the PIT joins.
             */
            satellites: string[];
            /**
             * Granularity
             * @description Snapshot grain; commonly 'day' or 'hour'. Free-form for now.
             * @default day
             */
            granularity: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** RejectBody */
        RejectBody: {
            /** Comment */
            comment: string;
        };
        /**
         * SatelliteDecision
         * @description A proposed raw-vault Satellite hanging off exactly one parent hub.
         */
        SatelliteDecision: {
            /**
             * Name
             * @description Target dbt model name, e.g. 'hub_conducting_equipment'.
             */
            name: string;
            /**
             * Source Table
             * @description Bare or fully-qualified source table this entity is derived from.
             */
            source_table: string;
            /** @default medium */
            confidence: components["schemas"]["DecisionConfidence"];
            /**
             * Rationale
             * @description Free-text justification produced by the agent (kept short).
             * @default
             */
            rationale: string;
            /** @default satellite */
            kind: components["schemas"]["EntityKind"];
            /**
             * Parent Hub
             * @description Name of the parent HubDecision this satellite describes.
             */
            parent_hub: string;
            /**
             * Hash Key
             * @description Hash-key column inherited from the parent hub.
             */
            hash_key: string;
            /**
             * Hashdiff
             * @description Hashdiff column protecting the descriptive payload.
             */
            hashdiff: string;
            /**
             * Payload
             * @description Descriptive (non-key) source columns tracked by this satellite.
             */
            payload: string[];
            /**
             * Effective From
             * @description Optional effective-from column for SCD2 semantics.
             */
            effective_from?: string | null;
        };
        /**
         * Severity
         * @description Issue severity. ERROR blocks approval; WARNING/INFO do not.
         * @enum {string}
         */
        Severity: "error" | "warning" | "info";
        /**
         * SourceSystem
         * @description Metadata about the upstream source system (mirrors poc YAML 'system').
         */
        SourceSystem: {
            /** System Id */
            system_id: string;
            /** System Name */
            system_name: string;
            /**
             * Source Type
             * @default delta
             */
            source_type: string;
            /** Catalog */
            catalog?: string | null;
            /** Schema Name */
            schema_name?: string | null;
            /**
             * Record Source
             * @description Value to stamp into the RECORD_SOURCE column downstream.
             */
            record_source?: string | null;
        };
        /**
         * TableChange
         * @description One row in the diff change-set.
         */
        TableChange: {
            /** Table Name */
            table_name: string;
            category: components["schemas"]["ChangeCategory"];
            /** @default low */
            risk: components["schemas"]["ChangeRisk"];
            /**
             * Column Diffs
             * @default []
             */
            column_diffs: components["schemas"]["ColumnDiff"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** ValidateRequest */
        ValidateRequest: {
            plan?: components["schemas"]["ModelingPlan-Input"] | null;
            /** Rendered Yaml */
            rendered_yaml?: string | null;
            /** Dbt Project Path */
            dbt_project_path?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationIssue
         * @description A single issue produced by one of the validator's deterministic checks.
         */
        ValidationIssue: {
            /**
             * Code
             * @description Stable machine-readable code (e.g. 'YAML_SYNTAX', 'ORPHAN_SAT', 'APPEND_ONLY_ON_EFF_SAT'). Used by the UI to look up help text.
             */
            code: string;
            severity: components["schemas"]["Severity"];
            /** Message */
            message: string;
            /**
             * Location
             * @description Free-text pointer to the offending node (e.g. 'satellites[3].parent_hub' or 'system_metadata.yml:L142').
             */
            location?: string | null;
            /**
             * Suggestion
             * @description Optional remediation hint shown in the UI.
             */
            suggestion?: string | null;
        };
        /**
         * ValidationReport
         * @description Complete output of Step 6 — Validator.
         */
        ValidationReport: {
            /** Plan Id */
            plan_id: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ValidationIssue"][];
            summary: components["schemas"]["CheckSummary"];
            /**
             * Checks Run
             * @description Names of the checks that actually ran (e.g. 'yaml_syntax', 'pydantic_schema', 'referential_integrity', 'dbt_parse').
             * @default []
             */
            checks_run: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validate_api_plans_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_plans_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelingPlan-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    architect_bv_api_plans_architect_bv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelingPlan-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BvProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_plans_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_plans__plan_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_plans__plan_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_changes_api_plans__plan_id__request_changes_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_for_api_history__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_catalogs_api_discovery_catalogs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["CatalogListResponse"];
                };
            };
        };
    };
    list_schemas_api_discovery_catalogs__catalog__schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: { catalog: string };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["SchemaListResponse"];
                };
            };
        };
    };
    snapshot_api_discovery_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotRequest"];
            };
        };
        responses: {
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    submit_for_review_api_plans__plan_id__submit_for_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: { plan_id: string };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitForReviewRequest"];
            };
        };
        responses: {
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"];
                };
            };
        };
    };
}
